# Generated by Django 5.2.1 on 2025-05-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offender",
            fields=[
                (
                    "plate_number",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("total_violations", models.IntegerField(default=1)),
                ("last_violation", models.DateTimeField(blank=True, null=True)),
                ("is_repeat_offender", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("violation_type", models.CharField(max_length=64)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("image_path", models.CharField(blank=True, max_length=256, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "plate_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="violations.offender",
                    ),
                ),
            ],
        ),
    ]
